In [28]:
print('hello')

hello

In [29]:
# Import library for date and time manipulation
import datetime

In [30]:
# Showing difference between datetime.date and string representation of date
print(datetime.date(2024,1,2))
print('2024-01-02')

2024-01-02
2024-01-02

In [31]:
# Printing a specific date and time using datetime.datetime
print(datetime.datetime(2024,1,2,14,30,26))

2024-01-02 14:30:26

In [32]:
# Prints the current date
print(datetime.date.today())

# Prints the current date and time
print(datetime.datetime.now())

2026-10-18
2026-10-18 22:05:50.229490

In [33]:
# Creating a string representation of a date and converting it to a datetime object
d1 = '2024-01-02'

# Converts string to datetime object
print(datetime.datetime.strptime(d1, '%Y-%m-%d'))

2024-01-02 00:00:00

In [34]:
# String with spaces instead of dashes
d1 = '2024 01 02'

# Converts string to datetime object with spaces instead of dashes
print(datetime.datetime.strptime(d1, '%Y %m %d'))

2024-01-02 00:00:00

In [35]:
# String with slashes instead of dashes
d1 = '2024/01/02' 

# Converts string to datetime object with slashes instead of dashes
print(datetime.datetime.strptime(d1, '%Y/%m/%d'))

2024-01-02 00:00:00

In [36]:
# String with slashes instead of dashes and time
d2 = '2024/01/02 09:35:02' 

# Converting string to datetime object with slashes instead of dashes and current time
print(datetime.datetime.strptime(d2, '%Y/%m/%d %H:%M:%S'))

2024-01-02 09:35:02

In [37]:
# Importing the time module to save the current time in seconds since the epoch (January 1, 1970)
import time

# Prints the current time in seconds since the epoch (January 1, 1970)
print(time.time())

1792353950.2539039

In [38]:
# Saving the current time in seconds since the epoch (January 1, 1970) to a variable
t1 = time.time()

# Prints the current time in seconds since the epoch (January 1, 1970)
print(t1) 

# Converts seconds since epoch to datetime object
print(datetime.datetime.fromtimestamp(t1))

1792353950.258705
2026-10-18 22:05:50.258705

In [39]:
# Creating a string representation of a date and time and converting it to a datetime object
d2 = '2024/01/02 09:35:02' 

# Converting string to datetime object with and time
d2_datetime = datetime.datetime.strptime(d2, '%Y/%m/%d %H:%M:%S') 

# Prints the datetime object
print(d2_datetime) 

# Converts datetime object to seconds since epoch
print(d2_datetime.timestamp())

2024-01-02 09:35:02
1704184502.0

In [40]:
# Importing the pandas library for data manipulation and analysis
import pandas as pd

In [41]:
# Reading a CSV file containing Bitcoin to USDT data into a pandas DataFrame
df = pd.read_csv('BTC-USDT.csv')
df

                date      open      high       low     close       volume
0      1502942400000   4261.48   4313.62   4261.32   4308.83    47.181009
1      1502946000000   4308.83   4328.69   4291.37   4315.32    23.234916
2      1502949600000   4330.29   4345.45   4309.37   4324.35     7.229691
3      1502953200000   4316.62   4349.99   4287.41   4349.99     4.443249
4      1502956800000   4333.32   4377.85   4333.32   4360.69     0.972807
...              ...       ...       ...       ...       ...          ...
51404  1688364000000  30673.61  30678.41  30606.00  30651.25  1036.522350
51405  1688367600000  30651.25  30759.80  30636.65  30667.19  1758.796390
51406  1688371200000  30667.19  30700.92  30599.07  30640.12  1390.909010
51407  1688374800000  30640.11  30670.00  30602.29  30610.61   833.620010
51408  1688378400000  30610.60  30623.08  30605.66  30615.85    91.875210

[51409 rows x 6 columns]

In [42]:
# Converts the 'date' column from milliseconds since epoch to datetime objects in UTC
df['date'] = pd.to_datetime(df['date'], unit='ms', utc=True)
df

# Prints the data type of the 'date' column
print(df['date'].dtype)

datetime64[ms, UTC]

In [43]:
# Creating a new column 'weekday' in the DataFrame that contains the day of the week for each date (0=Monday, 6=Sunday)
df['weekday'] = df['date'].dt.weekday
df

,date,open,high,low,close,volume,weekday
0,2017-08-17 04:00:00+00:00,4261.48,4313.62,4261.32,4308.83,47.181009,3
1,2017-08-17 05:00:00+00:00,4308.83,4328.69,4291.37,4315.32,23.234916,3
2,2017-08-17 06:00:00+00:00,4330.29,4345.45,4309.37,4324.35,7.229691,3
3,2017-08-17 07:00:00+00:00,4316.62,4349.99,4287.41,4349.99,4.443249,3
4,2017-08-17 08:00:00+00:00,4333.32,4377.85,4333.32,4360.69,0.972807,3
...,...,...,...,...,...,...,...
51404,2023-07-03 06:00:00+00:00,30673.61,30678.41,30606.00,30651.25,1036.522350,0
51405,2023-07-03 07:00:00+00:00,30651.25,30759.80,30636.65,30667.19,1758.796390,0
51406,2023-07-03 08:00:00+00:00,30667.19,30700.92,30599.07,30640.12,1390.909010,0
51407,2023-07-03 09:00:00+00:00,30640.11,30670.00,30602.29,30610.61,833.620010,0
51408,2023-07-03 10:00:00+00:00,30610.60,30623.08,30605.66,30615.85,91.875210,0

In [44]:
# Creating a mapping of numeric weekday values to their corresponding day names
day_name_map = {
    0: 'Monday',
    1: 'Tuesday',
    2: 'Wednesday',
    3: 'Thursday',
    4: 'Friday',
    5: 'Saturday',
    6: 'Sunday'
}

# Maps the numeric weekday values to their corresponding day names using the day_name_map dictionary
df['weekday'] = df['weekday'].map(day_name_map) 
df

,date,open,high,low,close,volume,weekday
0,2017-08-17 04:00:00+00:00,4261.48,4313.62,4261.32,4308.83,47.181009,Thursday
1,2017-08-17 05:00:00+00:00,4308.83,4328.69,4291.37,4315.32,23.234916,Thursday
2,2017-08-17 06:00:00+00:00,4330.29,4345.45,4309.37,4324.35,7.229691,Thursday
3,2017-08-17 07:00:00+00:00,4316.62,4349.99,4287.41,4349.99,4.443249,Thursday
4,2017-08-17 08:00:00+00:00,4333.32,4377.85,4333.32,4360.69,0.972807,Thursday
...,...,...,...,...,...,...,...
51404,2023-07-03 06:00:00+00:00,30673.61,30678.41,30606.00,30651.25,1036.522350,Monday
51405,2023-07-03 07:00:00+00:00,30651.25,30759.80,30636.65,30667.19,1758.796390,Monday
51406,2023-07-03 08:00:00+00:00,30667.19,30700.92,30599.07,30640.12,1390.909010,Monday
51407,2023-07-03 09:00:00+00:00,30640.11,30670.00,30602.29,30610.61,833.620010,Monday
51408,2023-07-03 10:00:00+00:00,30610.60,30623.08,30605.66,30615.85,91.875210,Monday

In [45]:
# Calculates the difference between the current date and the previous date in the 'date' column
df['date_diff'] = df['date'] - df['date'].shift(1) 
df

,date,open,high,low,close,volume,weekday,date_diff
0,2017-08-17 04:00:00+00:00,4261.48,4313.62,4261.32,4308.83,47.181009,Thursday,NaT
1,2017-08-17 05:00:00+00:00,4308.83,4328.69,4291.37,4315.32,23.234916,Thursday,0 days 01:00:00
2,2017-08-17 06:00:00+00:00,4330.29,4345.45,4309.37,4324.35,7.229691,Thursday,0 days 01:00:00
3,2017-08-17 07:00:00+00:00,4316.62,4349.99,4287.41,4349.99,4.443249,Thursday,0 days 01:00:00
4,2017-08-17 08:00:00+00:00,4333.32,4377.85,4333.32,4360.69,0.972807,Thursday,0 days 01:00:00
...,...,...,...,...,...,...,...,...
51404,2023-07-03 06:00:00+00:00,30673.61,30678.41,30606.00,30651.25,1036.522350,Monday,0 days 01:00:00
51405,2023-07-03 07:00:00+00:00,30651.25,30759.80,30636.65,30667.19,1758.796390,Monday,0 days 01:00:00
51406,2023-07-03 08:00:00+00:00,30667.19,30700.92,30599.07,30640.12,1390.909010,Monday,0 days 01:00:00
51407,2023-07-03 09:00:00+00:00,30640.11,30670.00,30602.29,30610.61,833.620010,Monday,0 days 01:00:00
51408,2023-07-03 10:00:00+00:00,30610.60,30623.08,30605.66,30615.85,91.875210,Monday,0 days 01:00:00

In [46]:
# Counts the occurrences of each unique value in the 'date_diff' column
df['date_diff'].value_counts()

date_diff
0 days 01:00:00    51354
0 days 00:00:00       26
0 days 02:00:00        9
0 days 03:00:00        5
0 days 04:00:00        3
0 days 07:00:00        2
0 days 11:00:00        2
0 days 08:00:00        2
0 days 05:00:00        2
1 days 10:00:00        1
0 days 09:00:00        1
0 days 06:00:00        1
Name: count, dtype: int64

In [47]:
# Filters the DataFrame to show rows where the 'date_diff' column is equal to '0 days 00:00:00'
print(df.loc[df['date_diff'] == '0 days 00:00:00'])

                           date      open      high       low     close  \
43372 2022-08-03 14:00:00+00:00  23341.12  23430.19  23207.29  23301.49
43399 2022-08-04 16:00:00+00:00  22931.68  22980.00  22527.00  22587.50
43414 2022-08-05 06:00:00+00:00  23189.77  23432.51  23188.90  23282.02
43423 2022-08-05 14:00:00+00:00  23053.25  23360.00  23022.50  23177.08
44332 2022-09-12 10:00:00+00:00  22167.34  22222.08  21970.43  22154.46
44668 2022-09-26 09:00:00+00:00  19273.55  19318.96  19063.64  19082.72
44721 2022-09-28 13:00:00+00:00  19072.62  19200.00  19012.00  19122.95
44936 2022-10-07 11:00:00+00:00  19995.97  20018.87  19959.28  19998.90
45271 2022-10-21 09:00:00+00:00  18981.00  19030.84  18900.00  19011.00
45476 2022-10-29 21:00:00+00:00  20850.71  20899.99  20840.01  20846.18
45517 2022-10-31 13:00:00+00:00  20699.23  20755.73  20300.00  20336.29
45755 2022-11-10 10:00:00+00:00  16694.14  16744.60  16340.00  16403.74
45849 2022-11-14 07:00:00+00:00  16639.75  16889.97  16385.11  16824.78
46190 2022-11-28 11:00:00+00:00  16197.21  16230.77  16190.97  16213.29
46285 2022-12-02 09:00:00+00:00  16964.56  16989.57  16956.00  16962.17
46357 2022-12-05 08:00:00+00:00  17313.34  17386.00  17300.00  17359.53
46748 2022-12-21 14:00:00+00:00  16847.57  16914.72  16723.00  16796.34
47249 2023-01-11 10:00:00+00:00  17446.86  17459.00  17435.18  17441.24
47374 2023-01-16 14:00:00+00:00  20827.47  20894.00  20756.00  20860.68
47827 2023-02-04 10:00:00+00:00  23340.02  23369.40  23331.24  23335.83
48424 2023-03-01 06:00:00+00:00  23695.14  23803.39  23666.00  23752.75
48478 2023-03-03 11:00:00+00:00  22352.09  22367.53  22300.14  22342.92
48717 2023-03-13 09:00:00+00:00  22191.11  22262.35  21813.88  21963.37
49244 2023-04-04 08:00:00+00:00  28021.31  28137.98  27931.20  28103.48
49940 2023-05-03 07:00:00+00:00  28600.02  28674.69  28582.44  28653.80
51143 2023-06-22 09:00:00+00:00  30096.69  30178.19  30057.08  30134.36

            volume    weekday date_diff
43372   8271.14791  Wednesday    0 days
43399   9877.28422   Thursday    0 days
43414   7956.52743     Friday    0 days
43423  12296.49544     Friday    0 days
44332  16864.98566     Monday    0 days
44668  26678.09152     Monday    0 days
44721  25643.91236  Wednesday    0 days
44936   6441.69152     Friday    0 days
45271  12323.68045     Friday    0 days
45476   4655.28797   Saturday    0 days
45517  26694.66317     Monday    0 days
45755  22802.70656   Thursday    0 days
45849  31586.51798     Monday    0 days
46190   6850.56846     Monday    0 days
46285   6427.60143     Friday    0 days
46357  15195.21734     Monday    0 days
46748  13977.67634  Wednesday    0 days
47249   6172.66996  Wednesday    0 days
47374  10008.38954     Monday    0 days
47827   6319.79876   Saturday    0 days
48424  11365.96869  Wednesday    0 days
48478   7581.26516     Friday    0 days
48717  35114.65542     Monday    0 days
49244   1579.58553    Tuesday    0 days
49940   1406.01574  Wednesday    0 days
51143   1614.21962   Thursday    0 days

In [48]:
# Groups the DataFrame by the 'weekday' column and calculates the mean of the 'volume' column for each group
df.groupby('weekday').agg({'volume':'mean'})

                volume
weekday
Friday     3525.469924
Monday     3444.452027
Saturday   2371.131363
Sunday     2445.885570
Thursday   3518.008325
Tuesday    3498.625967
Wednesday  3617.011268

In [49]:
# Creating a new column nyse (New York Stock Exchange) that consists of True or False values based on whether the time 
# in the 'date' column falls within the NYSE trading hours (9:30 AM to 4:00 PM Eastern Time)
df['nyse'] = df['date'].apply(lambda x: x.time() >= datetime.time(9, 30) and x.time() <= datetime.time(16, 0))
df

,date,open,high,low,close,volume,weekday,date_diff,nyse
0,2017-08-17 04:00:00+00:00,4261.48,4313.62,4261.32,4308.83,47.181009,Thursday,NaT,False
1,2017-08-17 05:00:00+00:00,4308.83,4328.69,4291.37,4315.32,23.234916,Thursday,0 days 01:00:00,False
2,2017-08-17 06:00:00+00:00,4330.29,4345.45,4309.37,4324.35,7.229691,Thursday,0 days 01:00:00,False
3,2017-08-17 07:00:00+00:00,4316.62,4349.99,4287.41,4349.99,4.443249,Thursday,0 days 01:00:00,False
4,2017-08-17 08:00:00+00:00,4333.32,4377.85,4333.32,4360.69,0.972807,Thursday,0 days 01:00:00,False
...,...,...,...,...,...,...,...,...,...
51404,2023-07-03 06:00:00+00:00,30673.61,30678.41,30606.00,30651.25,1036.522350,Monday,0 days 01:00:00,False
51405,2023-07-03 07:00:00+00:00,30651.25,30759.80,30636.65,30667.19,1758.796390,Monday,0 days 01:00:00,False
51406,2023-07-03 08:00:00+00:00,30667.19,30700.92,30599.07,30640.12,1390.909010,Monday,0 days 01:00:00,False
51407,2023-07-03 09:00:00+00:00,30640.11,30670.00,30602.29,30610.61,833.620010,Monday,0 days 01:00:00,False
51408,2023-07-03 10:00:00+00:00,30610.60,30623.08,30605.66,30615.85,91.875210,Monday,0 days 01:00:00,True

In [ ]:
# Vectorized dt.time version of the above code, which is faster and more efficient than using apply() with a lambda function.
# Creating a new column 'date_nyse' that converts the 'date' column to New York time zone
df['date_nyse'] = df['date'].dt.tz_convert('America/New_York')

# Extracting the time component from the 'date_nyse' column and storing it in a new variable 'time_col'
time_col = df['date_nyse'].dt.time

# Creating a column 'nyse' that consists of True or False values based on whether the time in the 'date' column falls within the NYSE trading hours
# (9:30 AM to 4:00 PM Eastern Time)
df['nyse'] = (time_col >= datetime.time(9, 30)) & (time_col <= datetime.time(16, 0))
df

# Creating a column 'euronext' that consists of True or False values based on whether the time 
# in the 'date' column falls within the Euronext trading hours 
# (9:00 AM to 5:30 PM Central European Time) but in American Eastern Time (CET is 6 hours ahead of EST, 
# so the trading hours in EST are 3:00 AM to 11:30 AM)
df['euronext'] = (time_col >= datetime.time(3, 0)) & (time_col <= datetime.time(11, 30))
df

# Creating a column 'tokyo' that consists of True or False values based on whether the time 
# in the 'date' column falls within the Tokyo Stock Exchange trading hours
# (9:00 AM to 3:00 PM Japan Standard Time) but in American Eastern Time (JST is 13 hours ahead of EST, 
# so the trading hours in EST are 8:00 PM to 2:00 AM)
# Since this range wraps around midnight, we need to check if the time is >= 20:00 OR <= 02:00, instead of using between() which assumes start <= end
df['tokyo'] = (time_col >= datetime.time(20, 0)) | (time_col <= datetime.time(2, 0))
df

,date,open,high,low,close,volume,weekday,date_diff,nyse,date_nyse,euronext,tokyo
0,2017-08-17 04:00:00+00:00,4261.48,4313.62,4261.32,4308.83,47.181009,Thursday,NaT,False,2017-08-17 00:00:00-04:00,False,True
1,2017-08-17 05:00:00+00:00,4308.83,4328.69,4291.37,4315.32,23.234916,Thursday,0 days 01:00:00,False,2017-08-17 01:00:00-04:00,False,True
2,2017-08-17 06:00:00+00:00,4330.29,4345.45,4309.37,4324.35,7.229691,Thursday,0 days 01:00:00,False,2017-08-17 02:00:00-04:00,False,True
3,2017-08-17 07:00:00+00:00,4316.62,4349.99,4287.41,4349.99,4.443249,Thursday,0 days 01:00:00,False,2017-08-17 03:00:00-04:00,True,False
4,2017-08-17 08:00:00+00:00,4333.32,4377.85,4333.32,4360.69,0.972807,Thursday,0 days 01:00:00,False,2017-08-17 04:00:00-04:00,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
51404,2023-07-03 06:00:00+00:00,30673.61,30678.41,30606.00,30651.25,1036.522350,Monday,0 days 01:00:00,False,2023-07-03 02:00:00-04:00,False,True
51405,2023-07-03 07:00:00+00:00,30651.25,30759.80,30636.65,30667.19,1758.796390,Monday,0 days 01:00:00,False,2023-07-03 03:00:00-04:00,True,False
51406,2023-07-03 08:00:00+00:00,30667.19,30700.92,30599.07,30640.12,1390.909010,Monday,0 days 01:00:00,False,2023-07-03 04:00:00-04:00,True,False
51407,2023-07-03 09:00:00+00:00,30640.11,30670.00,30602.29,30610.61,833.620010,Monday,0 days 01:00:00,False,2023-07-03 05:00:00-04:00,True,False
51408,2023-07-03 10:00:00+00:00,30610.60,30623.08,30605.66,30615.85,91.875210,Monday,0 days 01:00:00,False,2023-07-03 06:00:00-04:00,True,False

In [51]:
# Compare columns 'nyse', 'euronext', and 'tokyo' by mean volume during days of the week when each market is open. 

df.groupby('weekday').agg({
    'nyse': 'mean',
    'euronext': 'mean',
    'tokyo': 'mean'
})

               nyse  euronext     tokyo
weekday
Friday     0.292318  0.375663  0.290551
Monday     0.290783  0.375476  0.291871
Saturday   0.291706  0.375187  0.291299
Sunday     0.291944  0.375221  0.291129
Thursday   0.292201  0.375375  0.290564
Tuesday    0.292343  0.375188  0.290706
Wednesday  0.292379  0.375154  0.290737

In [ ]:
# Alternatively, you can use the following code to compare the mean volume for each market during days of the week when each market is open:
print(df[df['nyse'] == True].groupby('weekday').agg({'volume': 'mean'}))

print(df[df['euronext'] == True].groupby('weekday').agg({'volume': 'mean'}))

print(df[df['tokyo'] == True].groupby('weekday').agg({'volume': 'mean'}))

                volume
weekday
Friday     4072.566896
Monday     3825.435820
Saturday   2398.841278
Sunday     2732.008468
Thursday   4121.045236
Tuesday    4118.964608
Wednesday  4390.782034
                volume
weekday
Friday     4260.048587
Monday     4055.340433
Saturday   2563.279939
Sunday     2564.880276
Thursday   4132.503243
Tuesday    4084.271754
Wednesday  4103.697858
                volume
weekday
Friday     2980.557558
Monday     2964.892036
Saturday   2269.398961
Sunday     2013.397581
Thursday   2866.662362
Tuesday    2968.066975
Wednesday  2884.231334

In [ ]:
# Alternative option to compare the mean volume for each market during days of the week when each market is open:
result = pd.DataFrame({
    'nyse': df[df['nyse']]['volume'].groupby(df['weekday']).mean(),
    'euronext': df[df['euronext']]['volume'].groupby(df['weekday']).mean(),
    'tokyo': df[df['tokyo']]['volume'].groupby(df['weekday']).mean()
})

print(result)

                  nyse     euronext        tokyo
weekday
Friday     4072.566896  4260.048587  2980.557558
Monday     3825.435820  4055.340433  2964.892036
Saturday   2398.841278  2563.279939  2269.398961
Sunday     2732.008468  2564.880276  2013.397581
Thursday   4121.045236  4132.503243  2866.662362
Tuesday    4118.964608  4084.271754  2968.066975
Wednesday  4390.782034  4103.697858  2884.231334